Implementation of Save_history, Get_history, and Clear use cases
Arnnav-A/207-Project pull request #11
Opened 2023-11-23 04:27 UTC by JG808

2023-11-25 04:55 UTC, Arnnav-A commented on src/app/Main.java
> +        SearchView searchView = SearchUseCaseFactory.create(viewManagerModel, searchViewModel, listingResultsViewModel, searchDataAccessObject, historyDataAccessObject, historyDataAccessObject, histo
Is there a way that can avoid passing the same argument 3 times?

2023-11-25 05:07 UTC, Arnnav-A requested changes
Get history controller and save controller contain unnecessary throws exception in method signature

2023-11-25 05:25 UTC, nicolasdiasm commented on src/entity/Listing.java
> +    Place getPlaceFromName(String name);
This method is not necessary anymore

2023-11-25 05:27 UTC, nicolasdiasm commented on src/entity/CommonListing.java
> +    @Override
This method is not useful anymore, as the implementation of the placeInfo use case was completely reformulated

2023-11-25 05:34 UTC, nicolasdiasm commented on src/view/SearchView.java
> +    final JButton clearHistory;
add controllers as instance attributes, just like we did with searchController

2023-11-25 05:35 UTC, nicolasdiasm commented on src/view/SearchView.java
> +                      GetHistoryController getHistoryController, ClearController clearController) {
add
this.(name of the controller) = (name of the controller);
for each controller now added as instance attributes

2023-11-25 06:02 UTC, nicolasdiasm requested changes
add controllers as instance attributes, just like we did with searchController

2023-11-25 06:02 UTC, nicolasdiasm commented on src/interface_adapter/clear/ClearPresenter.java
> +        response.message();
Related to my comment in the output data of the clear use case

2023-11-25 16:20 UTC, Arnnav-A approved these changes

2023-11-26 15:32 UTC, nicolasdiasm approved these changes
We can make this changes after merging it as they are mostly related to clean architecture

2023-11-26 15:32 UTC, merged