Improving Clean Architecture application for history use cases
Arnnav-A/207-Project pull request #20
Opened 2023-11-26 19:24 UTC by Arnnav-A

I have added the required state and view model classes for the use cases, along with moving the UI calls to the view class instead of the output data.

2023-11-26 22:01 UTC, JG808 approved these changes

2023-11-27 14:56 UTC, nicolasdiasm requested changes
Mainly formatting issues.
Also change the name of the packages of clear to indicate that it is related to search history

2023-11-27 14:56 UTC, nicolasdiasm commented on src/interface_adapter/clear/ClearPresenter.java
>      private final SearchViewModel searchViewModel;
Add a line.

2023-11-27 14:56 UTC, nicolasdiasm commented on src/interface_adapter/clear/ClearPresenter.java
> +        ClearState state =new ClearState();
Add a space.

2023-11-27 14:56 UTC, nicolasdiasm commented on src/interface_adapter/clear/ClearViewModel.java
> +public class ClearViewModel extends ViewModel {
Add a new line.

2023-11-27 14:56 UTC, nicolasdiasm commented on src/interface_adapter/clear/ClearViewModel.java
> +    private ClearState state = new ClearState();
Add a new line.

2023-11-27 14:56 UTC, nicolasdiasm commented on src/interface_adapter/clear/ClearViewModel.java
> +    }
Add a new line.

2023-11-27 14:56 UTC, nicolasdiasm commented on src/interface_adapter/clear/ClearViewModel.java
> +    private final PropertyChangeSupport support = new PropertyChangeSupport(this);
Add a new line.

2023-11-27 14:56 UTC, nicolasdiasm commented on src/interface_adapter/get_history/GetHistoryPresenter.java
>  public class GetHistoryPresenter implements GetHistoryOutputBoundary {
Add a new line.

2023-11-27 14:56 UTC, nicolasdiasm commented on src/interface_adapter/get_history/GetHistoryPresenter.java
> +    public GetHistoryPresenter(SearchViewModel searchViewModel, ViewManagerModel viewManagerModel, GetHistoryViewModel getHistoryViewModel) {
Add a new line before it.

2023-11-27 14:56 UTC, nicolasdiasm commented on src/use_case/clear_history/ClearOutputData.java
>  public class ClearOutputData {
Add a new line.

2023-11-27 15:01 UTC, merged